# Generated by Django 5.0.6 on 2024-08-02 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_remove_user_orders_count_user_logged_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 57, 55, 31556, tzinfo=datetime.timezone.utc)),
        ),
    ]
