# Generated by Django 5.0.6 on 2024-08-02 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_user_device_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 15, 1, 18, 947004, tzinfo=datetime.timezone.utc)),
        ),
    ]
